import { SchemaField } from './schema-types';

export const ATRIBUTO_SCHEMA: SchemaField[] = [
  {
    key: 'id_atributo',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'id_entidad',
    label: 'Entidad',
    type: 'select',
    required: true,
    fk: 'entidad',
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'nombre_entidad',
    label: 'Entidad',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 3,
  },
  {
    key: 'nombre_columna',
    label: 'Nombre columna',
    type: 'text',
    required: true,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 4,
  },
  {
    key: 'tipo_dato',
    label: 'Tipo de dato',
    type: 'text',
    required: false,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 5,
  },
  {
    key: 'es_auditable',
    label: '¿Auditable?',
    type: 'checkbox',
    required: false,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 6,
  },
  {
    key: 'id_estado',
    label: 'Estado',
    type: 'select',
    required: true,
    fk: 'estado',
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 7,
  },
  {
    key: 'nombre_estado',
    label: 'Estado',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 8,
  },
  {
    key: 'ver_en_crear',
    label: 'Ver en crear',
    type: 'checkbox',
    required: false,
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 9,
  },
  {
    key: 'ver_en_editar',
    label: 'Ver en editar',
    type: 'checkbox',
    required: false,
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 10,
  },
  {
    key: 'ver_en_lista',
    label: 'Ver en lista',
    type: 'checkbox',
    required: false,
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 11,
  },
  {
    key: 'ver_en_detalle',
    label: 'Ver en detalle',
    type: 'checkbox',
    required: false,
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 12,
  },
  {
    key: 'es_fk',
    label: '¿Es FK?',
    type: 'checkbox',
    required: false,
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 13,
  },
  {
    key: 'fk_tabla_referencia',
    label: 'Tabla referencia',
    type: 'text',
    required: false,
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 14,
  },
  {
    key: 'fk_columna_mostrar',
    label: 'Columna mostrar',
    type: 'text',
    required: false,
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 15,
  },
];
