import { SchemaField } from './schema-types';

export const AUDITORIA_SCHEMA: SchemaField[] = [
  {
    key: 'id_auditoria',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'id_entidad',
    label: 'Entidad',
    type: 'select',
    required: true,
    fk: 'entidad',
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'nombre_entidad',
    label: 'Entidad',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 3,
  },
  {
    key: 'id_registro',
    label: 'ID Registro',
    type: 'number',
    required: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 4,
  },
  {
    key: 'id_usuario',
    label: 'Usuario',
    type: 'select',
    required: false,
    fk: 'usuario',
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 5,
  },
  {
    key: 'nombre_usuario',
    label: 'Usuario',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 6,
  },
  {
    key: 'accion',
    label: 'Accin',
    type: 'text',
    required: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 7,
  },
  {
    key: 'datos_anteriores',
    label: 'Datos anteriores',
    type: 'json',
    required: false,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 8,
  },
  {
    key: 'datos_nuevos',
    label: 'Datos nuevos',
    type: 'json',
    required: false,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 9,
  },
  {
    key: 'fecha',
    label: 'Fecha',
    type: 'datetime',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 10,
  },
  {
    key: 'direccion_ip',
    label: 'IP',
    type: 'text',
    required: false,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 11,
  },
];
