import { SchemaField } from './schema-types';

export const CONFIGURACION_SCHEMA: SchemaField[] = [
  {
    key: 'id_configuracion',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'id_usuario',
    label: 'Usuario',
    type: 'select',
    required: false,
    fk: 'usuario',
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'nombre_usuario',
    label: 'Usuario',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 3,
  },
  {
    key: 'id_estado',
    label: 'Estado',
    type: 'select',
    required: false,
    fk: 'estado',
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 4,
  },
  {
    key: 'nombre_estado',
    label: 'Estado',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 5,
  },
  {
    key: 'clave',
    label: 'Clave',
    type: 'text',
    required: true,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 6,
  },
  {
    key: 'valor',
    label: 'Valor',
    type: 'textarea',
    required: false,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 7,
  },
  {
    key: 'descripcion',
    label: 'Descripción',
    type: 'text',
    required: false,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 8,
  },
  {
    key: 'tipo',
    label: 'Tipo',
    type: 'select',
    required: false,
    options: [
      { value: 'string', label: 'Texto' },
      { value: 'number', label: 'Número' },
      { value: 'boolean', label: 'Booleano' },
      { value: 'json', label: 'JSON' },
      { value: 'select', label: 'Select' },
      { value: 'file', label: 'Archivo' },
      { value: 'date', label: 'Fecha' },
      { value: 'time', label: 'Hora' },
    ],
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 9,
  },
  {
    key: 'publico',
    label: '¿Público?',
    type: 'checkbox',
    required: false,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 10,
  },
  {
    key: 'protegido',
    label: '¿Protegido?',
    type: 'checkbox',
    required: false,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 11,
  },
  {
    key: 'creado_por',
    label: 'Creado por',
    type: 'select',
    required: false,
    fk: 'usuario',
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 12,
  },
  {
    key: 'fecha_creacion',
    label: 'Fecha creación',
    type: 'datetime',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 13,
  },
  {
    key: 'actualizado_por',
    label: 'Actualizado por',
    type: 'select',
    required: false,
    fk: 'usuario',
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 14,
  },
  {
    key: 'fecha_actualizacion',
    label: 'Fecha actualización',
    type: 'datetime',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 15,
  },
];
