import { SchemaField } from './schema-types';

export const ENTIDAD_SCHEMA: SchemaField[] = [
  {
    key: 'id_entidad',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'nombre_tabla',
    label: 'Nombre tabla',
    type: 'text',
    required: true,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'alias_nombre',
    label: 'Alias',
    type: 'text',
    required: true,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 3,
  },
  {
    key: 'id_estado',
    label: 'Estado',
    type: 'select',
    required: true,
    fk: 'estado',
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 4,
  },
  {
    key: 'nombre_estado',
    label: 'Estado',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 5,
  },
  {
    key: 'descripcion',
    label: 'Descripcin',
    type: 'textarea',
    required: false,
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 6,
  },
];
