import { SchemaField } from './schema-types';

export const ESTADO_SCHEMA: SchemaField[] = [
  {
    key: 'id_estado',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'nombre',
    label: 'Nombre',
    type: 'text',
    required: true,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'tipo_entidad',
    label: 'Tipo entidad',
    type: 'select',
    required: true,
    options: [
      { value: 'SISTEMA', label: 'Sistema' },
      { value: 'VIVIENDA', label: 'Vivienda' },
      { value: 'USUARIO', label: 'Usuario' },
    ],
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 3,
  },
  {
    key: 'descripcion',
    label: 'Descripción',
    type: 'text',
    required: false,
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 4,
  },
  {
    key: 'id_applicaciones_sitio',
    label: 'Aplicación sitio',
    type: 'select',
    required: false,
    fk: 'aplicacion-sitio',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 5,
  },
  {
    key: 'nombre_applicaciones_sitio',
    label: 'Nombre aplicación sitio',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 6,
  },
];
