import { SchemaField } from './schema-types';

export const HISTORIAL_ACCION_SCHEMA: SchemaField[] = [
  {
    key: 'id_accion',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'id_usuario',
    label: 'Usuario',
    type: 'select',
    required: true,
    fk: 'usuario',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'accion',
    label: 'Acción',
    type: 'text',
    required: true,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 3,
  },
  {
    key: 'descripcion',
    label: 'Descripción',
    type: 'text',
    required: false,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 4,
  },
  {
    key: 'fecha',
    label: 'Fecha',
    type: 'datetime',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 5,
  },
  {
    key: 'direccion_ip',
    label: 'IP',
    type: 'text',
    required: false,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 6,
  },
];
