import { SchemaField } from './schema-types';

export const HISTORIAL_ACCESO_SCHEMA: SchemaField[] = [
  {
    key: 'id_acceso',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'id_usuario',
    label: 'Usuario',
    type: 'select',
    required: true,
    fk: 'usuario',
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'nombre_usuario',
    label: 'Usuario',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 3,
  },
  {
    key: 'fecha_entrada',
    label: 'Fecha entrada',
    type: 'datetime',
    required: false,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 4,
  },
  {
    key: 'fecha_salida',
    label: 'Fecha salida',
    type: 'datetime',
    required: false,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 5,
  },
  {
    key: 'direccion_ip',
    label: 'IP',
    type: 'text',
    required: false,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 6,
  },
  {
    key: 'user_agent',
    label: 'User Agent',
    type: 'text',
    required: false,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 7,
  },
];
