import { SchemaField } from './schema-types';

export const JERARQUIA_SCHEMA: SchemaField[] = [
  {
    key: 'id_jerarquia',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'id_jerarquia_padre',
    label: 'Jerarquía padre',
    type: 'select',
    required: false,
    fk: 'jerarquia',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'nombre_jerarquia_padre',
    label: 'Nombre jerarquía padre',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 3,
  },
  {
    key: 'id_estado',
    label: 'Estado',
    type: 'select',
    required: false,
    fk: 'estado',
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 4,
  },
  {
    key: 'nombre_estado',
    label: 'Nombre estado',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 5,
  },
  {
    key: 'nombre',
    label: 'Nombre',
    type: 'text',
    required: true,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 6,
  },
  {
    key: 'descripcion',
    label: 'Descripción',
    type: 'text',
    required: false,
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 7,
  },
];
