import { SchemaField } from './schema-types';

export const MENU_SCHEMA: SchemaField[] = [
  {
    key: 'id_menu',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'nombre',
    label: 'Nombre',
    type: 'text',
    required: true,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'id_menu_padre',
    label: 'Menú padre',
    type: 'select',
    required: false,
    fk: 'menu',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 3,
  },
  {
    key: 'nombre_menu_padre',
    label: 'Menú padre',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 4,
  },
  {
    key: 'id_aplicacion',
    label: 'Aplicación',
    type: 'select',
    required: false,
    fk: 'aplicacion-sitio',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 5,
  },
  {
    key: 'nombre_aplicacion',
    label: 'Aplicación',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 6,
  },
  {
    key: 'id_estado',
    label: 'Estado',
    type: 'select',
    required: false,
    fk: 'estado',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 7,
  },
  {
    key: 'nombre_estado',
    label: 'Estado',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 8,
  },
  {
    key: 'url',
    label: 'URL',
    type: 'text',
    required: false,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 9,
  },
  {
    key: 'orden',
    label: 'Orden',
    type: 'number',
    required: false,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 10,
  },
  {
    key: 'icono',
    label: 'Icono',
    type: 'text',
    required: false,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 11,
  },
];
