import { SchemaField } from './schema-types';

export const ROLE_PERMISO_SCHEMA: SchemaField[] = [
  {
    key: 'id_rol_permiso',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'id_rol',
    label: 'Rol',
    type: 'select',
    required: true,
    fk: 'role',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'nombre_rol',
    label: 'Rol',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 3,
  },
  {
    key: 'id_permiso',
    label: 'Permiso',
    type: 'select',
    required: true,
    fk: 'permiso',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 4,
  },
  {
    key: 'nombre_permiso',
    label: 'Nombre permiso',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 5,
  },
  {
    key: 'id_estado',
    label: 'Estado',
    type: 'select',
    required: false,
    fk: 'estado',
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 6,
  },
  {
    key: 'nombre_estado',
    label: 'Nombre estado',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 7,
  },
];
