import { SchemaField } from './schema-types';

export const SESION_ACTIVA_SCHEMA: SchemaField[] = [
  {
    key: 'id_sesion',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'id_usuario',
    label: 'Usuario',
    type: 'select',
    required: true,
    fk: 'usuario',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'token_hash',
    label: 'Token',
    type: 'text',
    required: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 3,
  },
  {
    key: 'fecha_expiracion',
    label: 'Expiración',
    type: 'datetime',
    required: true,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 4,
  },
  {
    key: 'creado_at',
    label: 'Creado',
    type: 'datetime',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 5,
  },
];
