import { SchemaField } from './schema-types';

export const SITIO_SCHEMA: SchemaField[] = [
  {
    key: 'id_sitio',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'id_estado',
    label: 'Estado',
    type: 'select',
    required: false,
    fk: 'estado',
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'nombre_estado',
    label: 'Nombre estado',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 3,
  },
  {
    key: 'nombre',
    label: 'Nombre',
    type: 'text',
    required: true,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 4,
  },
  {
    key: 'codigo',
    label: 'Código',
    type: 'text',
    required: false,
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 5,
  },
  {
    key: 'descripcion',
    label: 'Descripción',
    type: 'textarea',
    required: false,
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 6,
  },
  {
    key: 'created_at',
    label: 'Creado',
    type: 'datetime',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 7,
  },
  {
    key: 'updated_at',
    label: 'Actualizado',
    type: 'datetime',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 8,
  },
];
