import { SchemaField } from './schema-types';

export const USUARIO_SCHEMA: SchemaField[] = [
  {
    key: 'id_usuario',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'nombre_usuario',
    label: 'Usuario',
    type: 'text',
    required: true,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'nombres',
    label: 'Nombres',
    type: 'text',
    required: false,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 3,
  },
  {
    key: 'apellidos',
    label: 'Apellidos',
    type: 'text',
    required: false,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 4,
  },
  {
    key: 'correo_electronico',
    label: 'Correo electrónico',
    type: 'text',
    required: true,
    verEnLista: true,
    verEnEditar: true,
    verEnCrear: true,
    orden: 5,
  },
  {
    key: 'hash_contrasena',
    label: 'Contraseña',
    type: 'text',
    required: true,
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 6,
  },
  {
    key: 'id_tipo_usuario',
    label: 'Tipo usuario',
    type: 'select',
    required: true,
    fk: 'tipo-usuario',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 7,
  },
  {
    key: 'nombre_tipo_usuario',
    label: 'Tipo Usuario',
    type: 'text',
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 8,
  },
  {
    key: 'id_rol',
    label: 'Rol',
    type: 'select',
    required: false,
    fk: 'rol',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 9,
  },
  {
    key: 'nombre_rol',
    label: 'Rol',
    type: 'text',
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 10,
  },
  {
    key: 'id_jerarquia',
    label: 'Jerarquía',
    type: 'select',
    required: false,
    fk: 'jerarquia',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 11,
  },
  {
    key: 'nombre_jerarquia',
    label: 'Jerarquía',
    type: 'text',
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 12,
  },
  {
    key: 'id_estado',
    label: 'Estado',
    type: 'select',
    required: false,
    fk: 'estado',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 13,
  },
  {
    key: 'nombre_estado',
    label: 'Estado',
    type: 'text',
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 14,
  },
  {
    key: 'img',
    label: 'Imagen',
    type: 'text',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 15,
  },
  {
    key: 'fecha_creacion',
    label: 'Fecha creación',
    type: 'datetime',
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 16,
  },
  {
    key: 'fecha_actualizacion',
    label: 'Fecha actualización',
    type: 'datetime',
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 17,
  },
  {
    key: 'fecha_cambio_contrasena',
    label: 'Fecha cambio contraseña',
    type: 'datetime',
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 18,
  },
  {
    key: 'deleted_at',
    label: 'Eliminado',
    type: 'datetime',
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 19,
  },
];
