import { SchemaField } from './schema-types';

export const USUARIO_APLICACION_SCHEMA: SchemaField[] = [
  {
    key: 'id_usuario_aplicacion',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'id_usuario',
    label: 'Usuario',
    type: 'select',
    required: true,
    fk: 'usuario',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'nombre_usuario',
    label: 'Usuario',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 3,
  },
  {
    key: 'id_aplicacion',
    label: 'Aplicación',
    type: 'select',
    required: true,
    fk: 'aplicacion-sitio',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 4,
  },
  {
    key: 'nombre_aplicacion',
    label: 'Aplicación',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 5,
  },
  {
    key: 'id_estado',
    label: 'Estado',
    type: 'select',
    required: false,
    fk: 'estado',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 6,
  },
  {
    key: 'nombre_estado',
    label: 'Estado',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 7,
  },
  {
    key: 'created_at',
    label: 'Creado',
    type: 'datetime',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 8,
  },
  {
    key: 'updated_at',
    label: 'Actualizado',
    type: 'datetime',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 9,
  },
];
