import { SchemaField } from './schema-types';

export const USUARIO_JERARQUIA_SCHEMA: SchemaField[] = [
  {
    key: 'id_usuario_jerarquia',
    label: 'ID',
    type: 'number',
    readonly: true,
    verEnLista: false,
    verEnEditar: false,
    verEnCrear: false,
    orden: 1,
  },
  {
    key: 'id_usuario',
    label: 'Usuario',
    type: 'select',
    required: true,
    fk: 'usuario',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 2,
  },
  {
    key: 'nombre_usuario',
    label: 'Usuario',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 3,
  },
  {
    key: 'id_jerarquia',
    label: 'Jerarquía',
    type: 'select',
    required: true,
    fk: 'jerarquia',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 4,
  },
  {
    key: 'nombre_jerarquia',
    label: 'Jerarquía',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 5,
  },
  {
    key: 'id_estado',
    label: 'Estado',
    type: 'select',
    required: false,
    fk: 'estado',
    verEnLista: false,
    verEnEditar: true,
    verEnCrear: true,
    orden: 6,
  },
  {
    key: 'nombre_estado',
    label: 'Estado',
    type: 'text',
    readonly: true,
    verEnLista: true,
    verEnEditar: false,
    verEnCrear: false,
    orden: 7,
  },
];
